repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: ['--branch', 'main']
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Run black formatter
        language_version: python3.8
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports"]
